### ISSUE TITLE
Do not directly require PHPUnit

### ISSUE THREAD

**Issue by lukasluecke** [matthiasnoback/phpunit-asynchronicity#12]
It would be great if this package would not directly require PHPUnit itself, as this leads to issues with the Symfony PHPUnit bridge. Maybe it could instead use `suggests` and `conflicts` depending on which versions it's compatible with?

**Comment by matthiasnoback** [comment]
Interesting; can you describe the issues? I think the change you suggested can be made, but it doesn't make a lot of sense, since the code in `src` actually depends on code from the `phpunit/phpunit` package. So without it, it wouldn't be very honest about the dependencies.

**Comment by lukasluecke** [comment]
The problem is that it often would install a different version in addition to the one used in a project already (which is not explicitly required at the root level, but instead inside of `symfony/phpunit-bridge`, which then leads to autoloading and other issues.

I'm honestly not sure what the right way to resolve this would be 😕 NPM has `peerDependencies` for this use-case (packages that need to be available in consumer projects).

**Comment by matthiasnoback** [comment]
Okay, I'd be happy to help you with this. If you like you can make a PR where `phpunit/phpunit` is only a suggested and a dev dependency. And indeed you can use conflicts to indicate that we need a recent version.
